apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: payobills-applications
  namespace: argo-cd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/payobills/argo-config
        revision: main
        files:
          - path: "apps/**/config.json"
  template:
    metadata:
      name: 'payobills-{{ if .metadata.labels.appName }}{{.metadata.labels.appName}}{{else}}{{.path.basename}}{{end}}'
    spec:
      syncPolicy:
        automated: {}
      destination:
        namespace: payobills
        server: https://kubernetes.default.svc
      project: payobills
      sources:
      - path: '{{.path.basename}}'
        chart: '{{.path.basename}}'
        repoURL: https://payobills.github.io/helm-charts
        targetRevision: '{{.metadata.labels.chartVersion}}'
        helm:
          valueFiles:
          - $values/apps/{{.path.basename}}/k8s/values.yaml
          - $argoConfig/apps/{{.path.basename}}/values.yaml
          valuesObject:
            openTelemetry:
              enabled: "false"
            image:
              repository: 'ghcr.io/payobills/{{if .metadata.labels.appType}}{{.metadata.labels.appType }}{{else }}{{"apps" }}{{end}}/{{.path.basename}}'
              pullPolicy: Always
              tag: '{{.metadata.labels.appVersion}}'
      - repoURL: 'https://github.com/payobills/payobills.git'
        targetRevision: main
        ref: values
      - repoURL: 'https://github.com/payobills/argo-config.git'
        targetRevision: main
        ref: argoConfig
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
